---
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8010/eureka

management:
  endpoints:
    web:
      exposure:
        include: info, health, hystrix.stream

server:
  port: 8081

spring:
  application:
    name: cw-info-service

http:
  rateLimiter:
    capacity: 1
    tokensAllowed: 1
    period: 1200

cw:
  baseUrl: https://api.crackwatch.com/api

cache:
  games:
    getGames:
      name: getGamesCache