eureka:
  server:
    enableSelfPreservation: true
  client:
    fetchRegistry: false
    registerWithEureka: false
    serviceUrl:
      defaultZone: http://localhost:8010/eureka
server:
  port: 8010
spring:
  application:
    name: discovery-service